#!/bin/bash

clear && echo -e "$ORA[~]$NEU - INSTALL BASE (1/5)"
docker build -t riscv-debian-buster:base -f Dockerfile.base . &>/dev/null
clear && echo -e "$GRE[+]$NEU - INSTALL BASE (1/5)\n$ORA[~]$NEU - INSTALL TOOLCHAIN (2/5)..."
docker build -t riscv-debian-buster:toolchain-builder -f Dockerfile.toolchain-builder . &>/dev/null
clear && echo -e "$GRE[+]$NEU - INSTALL BASE (1/5)\n$GRE[+]$NEU - INSTALL TOOLCHAIN (2/5)\n$ORA[~]$NEU - INSTALL DEV-PLATFORM (3/5)..."
docker build -t riscv-debian-buster:dev-platform -f Dockerfile.dev-platform . &>/dev/null
clear && echo -e "$GRE[+]$NEU - INSTALL BASE (1/5)\n$GRE[+]$NEU - INSTALL TOOLCHAIN (2/5)\n$GRE[+]$NEU - INSTALL DEV-PLATFORM (3/5)\n$ORA[~]$NEU - INSTALL CI-PLATFORM (4/5)..."
docker build -t riscv-debian-buster:ci-platform -f Dockerfile.ci-platform . &>/dev/null
clear && echo -e "$GRE[+]$NEU - INSTALL BASE (1/5)\n$GRE[+]$NEU - INSTALL TOOLCHAIN (2/5)\n$GRE[+]$NEU - INSTALL DEV-PLATFORM (3/5)\n$GRE[+]$NEU - INSTALL CI-PLATFORM (4/5)\n$ORA[~]$NEU - INSTALL CI-PLATFORM-VERILATOR-SPIKE (5/5)..."
docker build -t riscv-debian-buster:ci-platform-verilator-spike -f Dockerfile.ci-platform-verilator-spike . &>/dev/null
clear && echo -e "$GRE[+]$NEU - INSTALL BASE (1/5)\n$GRE[+]$NEU - INSTALL TOOLCHAIN (2/5)\n$GRE[+]$NEU - INSTALL DEV-PLATFORM (3/5)\n$GRE[+]$NEU - INSTALL CI-PLATFORM (4/5)\n$GRE[+]$NEU - INSTALL CI-PLATFORM-VERILATOR-SPIKE (5/5)"
